---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: machinist
  labels:
    app.kubernetes.io/partition: platformatic
    app.kubernetes.io/instance: machinist
spec:
  selector:
    matchLabels:
      app.kubernetes.io/partition: platformatic
      app.kubernetes.io/instance: machinist
  template:
    metadata:
      labels:
        app.kubernetes.io/partition: platformatic
        app.kubernetes.io/instance: machinist
    spec:
      containers:
        - name: machinist
          image: platformatic/machinist:latest
          imagePullPolicy: Always
          env:
            - name: PLT_PORT
              value: "3000"
            - name: PLT_LOGGER_LEVEL
              value: "warn"
            - name: PLT_DISABLE_EVENT_EXPORT
              value: "true"
          ports:
            - name: http
              protocol: TCP
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: machinist
  labels:
    app.kubernetes.io/partition: platformatic
    app.kubernetes.io/instance: machinist
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/partition: platformatic
    app.kubernetes.io/instance: machinist

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plt-pod-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plt-pod-manager
rules:
  - apiGroups:
      - ""
      - apps
      - networking.k8s.io
    resources:
      - pods
      - deployments
      - replicasets
      - replicationcontrollers
      - ingresses
      - services
    verbs:
      - get
      - list
  - apiGroups:
      - ""
      - apps
    resources:
      - deployments
      - replicasets
      - replicationcontrollers
      - pods
    verbs:
      - update
      - patch
  # Skew protection auto-cleanup: delete expired Deployments and Services
  - apiGroups:
      - ""
      - apps
    resources:
      - deployments
      - services
    verbs:
      - delete
  # Gateway API permissions for skew protection (opt-in).
  # Only used when skew protection is enabled in ICC.
  # Safe to include even if Gateway API CRDs are not installed -
  # K8s silently ignores RBAC rules for unknown API groups.
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gateways
    verbs:
      - get
      - list

# If apps are going to be deployed in a namespace that is different from machinist
# then the RoleBinding will need to have the namespace set
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plt-pod-manager
  #namespace: ""
subjects:
  - kind: ServiceAccount
    name: plt-pod-manager
roleRef:
  kind: ClusterRole
  name: plt-pod-manager
  apiGroup: rbac.authorization.k8s.io
