name: Main branch
on:
  push:
    branches:
      - main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build-image:
    needs: [run-tests]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 'Setup QEMU'
        uses: docker/setup-qemu-action@v3
      - name: 'Setup Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build tags'
        run: |
          echo REPOSITORY_NAME=${GITHUB_REPOSITORY#*\/} >> $GITHUB_ENV
      - name: 'Build and push'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/platformatic/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
